// Generated by https://quicktype.io


export interface Product {
    id:    number;
    title: string;
    image: string;
}
export interface ProductsDBResponse {
    products:   Product[];
}

export interface Category {
    id:    number;
    title: string;
    image: string;
}
